background: "#2e3440"
color: "#eceff4"
border: "#8fbcbb"
# Theming
font: DroidSansM Nerd Font Mono 12
separator: " ➜ "
border_width: 4
corner_r: 10
padding: 15 # Defaults to corner_r
rows_per_column: 5 # No limit by default
column_padding: 25 # Defaults to padding

# Anchor and margin
anchor: center # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0

# namespace to use for the layer shell surface
# namespace: "wlr_which_key"

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: true

# Try to guess the correct keyboard layout to use. Default is `false`.
auto_kbd_layout: true

menu:
  - key: "n"
    desc: Noctalia
    submenu:
      - key: "w"
        desc: Wallpaper
        submenu:
          - key: "w"
            desc: Random wallpaper 
            cmd: qs -c noctalia-shell ipc call wallpaper random all
          - key: "s"
            desc: Wallpaper settings 
            cmd: qs -c noctalia-shell ipc call wallpaper toggle
      - key: "m"
        desc: Toggle dark/light mode
        cmd: qs -c noctalia-shell ipc call darkMode toggle
      - key: "c"
        desc: Pick and set color scheme
        cmd: ~/.config/noctalia/scripts/pick-colorscheme.sh
      - key: "s"
        desc: Toggle settings window
        cmd: qs -c noctalia-shell ipc call settings toggle
  - key: "w"
    desc: Work
    submenu:
      - key: "s"
        desc: Start work applications
        cmd: ~/bin/start-rtk.sh
      - key: "k"
        desc: Kill work applications
        cmd: ~/bin/kill-rtk.sh 
      - key: "f"
        desc: Focus an app
        submenu:
        - key: "c"
          desc: YuChat
          cmd: niri msg action focus-window --id $(niri msg --json windows | jq -r '.[] | select(.workspace_id==4) | select(.app_id=="YuChat") | .id' | sort | head -1)
        - key: "t"
          desc: TrueConf
          cmd: niri msg action focus-window --id $(niri msg --json windows | jq -r '.[] | select(.workspace_id==4) | select(.app_id=="TrueConf") | .id' | sort | head -1)
        - key: "v"
          desc: Vivaldi
          cmd: niri msg action focus-window --id $(niri msg --json windows | jq -r '.[] | select(.workspace_id==4) | select(.app_id=="vivaldi-stable") | .id')
 
        
