[bar]
order = ["default"]

[bar.default]
capsule_foreground = "on_surface_variant"
capsule_padding = 12.0
center = ["clock", "group:g1", "weather"]
end = ["tray", "group:g2"]
font_weight = 700
margin_edge = 8
margin_ends = 8
padding = 8
scale = 1.1
start = ["workspaces", "taskbar"]
widget_spacing = 12

[[bar.default.capsule_group]]
fill = "secondary"
foreground = "on_secondary"
id = "g1"
members = ["cpu", "ram", "temp"]
opacity = 1.0
padding = 12.0

[[bar.default.capsule_group]]
fill = "surface"
foreground = "on_surface"
id = "g2"
members = [
  "notifications",
  "volume",
  "network",
  "bluetooth",
  "battery",
  "keyboard_layout",
]
opacity = 1.0
padding = 12.0

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[desktop_widgets]
enabled = false

[dock]
launcher_position = "start"

[hooks]
# colors_changed = "~/.config/noctalia/scripts/set-color-scheme.sh"
# theme_mode_changed = "~/.config/noctalia/scripts/set-color-scheme.sh"

[idle]
behavior_order = ["lock", "screen-off", "suspend", "Screensaver"]
pre_action_fade_seconds = 1.0

[idle.behavior.Screensaver]
action = "command"
command = "/home/dmitriy/bin/screensaver"
enabled = true
resume_command = "niri msg --json windows | jq -r '.[] | select(.app_id == \"Screensaver\") | .id' | xargs -I {} niri msg action close-window --id {} && rm /home/dmitriy/.local/state/noctalia/screensaver.lock"
timeout = 120

[idle.behavior.lock]
action = "lock"
enabled = false
timeout = 600

[idle.behavior.screen-off]
action = "screen_off"
enabled = false
timeout = 660

[idle.behavior.suspend]
action = "suspend"
enabled = false
lock_before_suspend = true
timeout = 900

[location]
auto_locate = true

[lockscreen]
blurred_desktop = true

[lockscreen_widgets]
enabled = false
schema_version = 2

[osd]
position = "top_right"

[plugins]
enabled = ["noctalia/wallhaven", "noctalia/kaomoji"]

[shell]
font_family = "DroidSansM Nerd Font"
password_style = "random"
polkit_agent = true
settings_show_advanced = true

[shell.animation]
enabled = false

[shell.greeter_sync]
auto_sync = true

[shell.launcher]
session_search = true

[shell.panel]
launcher_compact = true
open_near_click_control_center = true
open_near_click_session = true
session_placement = "centered"
wallpaper_placement = "centered"

[shell.screen_corners]
enabled = true

[theme]
[theme.templates]
builtin_ids = ["btop", "gtk3", "gtk4", "niri", "qt"]
community_ids = [
  "pywalfox",
  "fuzzel",
  "discord",
  "papirus-icons",
  "yazi",
  "zathura",
]

[wallpaper]
directory = "/home/dmitriy/Pictures/Wallpapers"
fill_mode = "span"

[weather]
auto_locate = true

[widget.active_window]
max_length = 400
title_scroll = "on_hover"

[widget.battery]
display_mode = "graphic"

[widget.clock]
format = "{:%Y-%m-%d %H:%M}"

[widget.control-center]
color = "primary"
glyph = "yin-yang-filled"

[widget.keyboard_layout]
show_icon = false

[widget.network]
show_label = false

[widget.taskbar]
only_active_workspace = true

[widget.volume]
show_label = false

[widget.workspaces]
display = "name"
max_label_chars = 20
minimal = true
scale = 1.2
