[config]

[theme]
[theme.templates.user.wlr-which-key]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/wlr-which-key.yaml"
output_path = "$XDG_CONFIG_HOME/wlr-which-key/theme.yaml"
post_hook = "$XDG_CONFIG_HOME/wlr-which-key/set-theme.sh"

[theme.templates.user.alacritty]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/alacritty.toml"
output_path = "$XDG_CONFIG_HOME/alacritty/themes/noctalia.custom.toml"

[theme.templates.user.telegram]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/telegram.tdesktop-theme"
output_path = "$XDG_CONFIG_HOME/telegram-desktop/themes/colors.tdesktop-theme"
post_hook = "$XDG_CONFIG_HOME/noctalia/scripts/telegram-template-apply.sh"

[theme.templates.user.zellij]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/zellij.kdl"
output_path = "$XDG_CONFIG_HOME/zellij/themes/matugen.kdl"
post_hook = "sed -Ei 's/rgb\\(([0-9]+), *([0-9]+), *([0-9]+)\\)/\\1 \\2 \\3/g' $XDG_CONFIG_HOME/zellij/themes/matugen.kdl && touch ~/.config/zellij/config.kdl"

[theme.templates.user.nvim]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/nvim.lua"
output_path = "$XDG_CONFIG_HOME/nvim/colors/matugen.lua"
