[config]

[theme]

# SDDM GREETER
[theme.templates.user.sddm]
input_path = "/usr/share/sddm/themes/noctalia/theme.template.conf"
output_path = "/usr/share/sddm/themes/noctalia/theme.conf"

[theme.templates.user.wlr-which-key]
input_path = "~/.config/noctalia/templates/wlr-which-key.yaml"
output_path = "~/.config/wlr-which-key/theme.yaml"
post_hook = "~/.config/wlr-which-key/set-theme.sh"

[theme.templates.user.alacritty]
input_path = "~/.config/noctalia/templates/alacritty.toml"
output_path = "~/.config/alacritty/themes/noctalia.custom.toml"

[theme.templates.user.telegram]
input_path = "~/.config/noctalia/templates/telegram.tdesktop-theme"
output_path = "~/.config/telegram-desktop/themes/noctalia.tdesktop-theme"

[theme.templates.user.zellij]
input_path = "~/.config/noctalia/templates/zellij.kdl"
output_path = "~/.config/zellij/themes/matugen.kdl"
post_hook = "sed -Ei 's/rgb\\(([0-9]+), *([0-9]+), *([0-9]+)\\)/\\1 \\2 \\3/g' ~/.config/zellij/themes/matugen.kdl && touch ~/.config/zellij/config.kdl"
